interfaces:
  - name: FastEthernet1/0
    ip: 192.168.1.1
    mask: 255.255.255.252

vrf_interfaces:
  - name: FastEthernet2/0
    ip: 192.168.2.1
    mask: 255.255.255.252
    vrf: Cust_B
    rd: "200:1"
    rt_both: "200:1"
    # rt_import: ["200:1"]
    # rt_export: ["200:1"]
    vrf_ospf: 300
    vrf_ospf_area: 1
    vrf_ospfid: 4.4.4.4

loopback: 1.1.1.1
l0_mask: 255.255.255.255
ospf_process: 1
ospf_area: 0