- name: Configuring OSPF on CE Router
  hosts: CE
  gather_facts: no

  tasks:
    - name: Turn up the interfaces
      cisco.ios.ios_config:
        parents: "interface {{item.name}}"
        lines:
          - "ip address {{item.ip}} {{item.mask}}"
          - no shutdown
        match: line
      loop: "{{interfaces}}"

    - name: Configure Loopback
      cisco.ios.ios_config:
        parents: interface Loopback0
        lines:
          - "ip address {{loopback}} {{l0_mask}}"
          - no shutdown
        match: line

    - name: OSPF process on CE router
      cisco.ios.ios_config:
        parents: "router ospf {{ospf_process}}"
        lines: 
          - "router-id {{loopback}}"
        match: line

    - name: activate ospf on CE interfaces
      cisco.ios.ios_config:
        parents: "interface {{item.name}}"
        lines:
          - "ip ospf {{ospf_process}} area {{ospf_area}}"
        match: line
      loop: "{{interfaces}}"