- name: configure the interface towards R5
  hosts: myhosts
  gather_facts: no
  collections:
    - cisco.ios
  
  tasks:
    - name: Turn on the interface
      cisco.ios.ios_config:
        parents: interface Loopback0
        lines:
          - ip address 1.1.1.1 255.255.255.255