- name: Configuring P routers
  hosts: P
  gather_facts: no

  tasks:
    - name: Turn up the interfaces
      cisco.ios.ios_config:
        parents: "interface {{item.name}}"
        lines:
          - "ip address {{item.ip}} {{item.mask}}"
          - no shutdown
        match: line
      loop: "{{interfaces}}"

    - name: Configure Loopback
      cisco.ios.ios_config:
        parents: interface Loopback0
        lines:
          - "ip address {{loopback}} {{l0_mask}}"
        match: line

    - name: OSPF process
      cisco.ios.ios_config:
        parents: "router ospf {{ospf_process}}"
        lines: 
          - "router-id {{loopback}}"
        match: line

    - name: activate ospf and MPLS on interfaces
      cisco.ios.ios_config:
        parents: "interface {{item.name}}"
        lines:
          - "ip ospf {{ospf_process}} area {{ospf_area}}"
          - mpls ip
        match: line
      loop: "{{interfaces}}"
    

    - name: Set MPLS LDP router-id to Loopback
      cisco.ios.ios_config:
        parents: []
        lines:
          - mpls ldp router-id Loopback 0
    
    - name: ospf and MPLS on loopback interfaces
      cisco.ios.ios_config:
        parents: interface Loopback0
        lines:
          - "ip ospf {{ospf_process}} area {{ospf_area}}"
        match: line
        
    - name: Save running-config to startup-config
      cisco.ios.ios_config:
        save_when: always